spring.cloud.stream:
  function:
    definition: domainProcessor
  bindings:
    domainProcessor-in-0:
      destination: web-domains
    domainProcessor-out-0:
      destination: active.web-domains
  kafka:
    bindings:
      domainProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      domainProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
#      consumer-properties:
#        spring.json.trusted.packages: "*"
##        key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#        value.deserializer: com.kafkatutorial.domainprocessor.custom.CustomJsonDeserializer
##        schema.registry.url: http://localhost:8081
#        specific.avro.reader: true
      brokers:
        - localhost:9091
        - localhost:9092

#spring:
#  kafka:
#    consumer:
#      properties:
#        spring.json.trusted.packages: com.kafkatutorial.domaincrawler.model.Domain